plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ritmo.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ritmo.mobile'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '2.0.1'
    }

    signingConfigs {
        ritmoRelease {
            storeFile file('../signing/ritmo.keystore')
            storePassword 'ritmo2026app'
            keyAlias 'ritmo'
            keyPassword 'ritmo2026app'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.ritmoRelease
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.ritmoRelease
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
